### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by dfmjndm** [haha114514/youtube_dl_hoshino#1]
181行报缩进错误

**Comment by dfmjndm** [comment]
[2022-05-02 15:03:16,268 nonebot] ERROR: unexpected unindent (youtube.py, line 181)
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/nonebot/plugin.py", line 274, in load_plugin
    module = importlib.import_module(module_path)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/hobot/hoshino/modules/youtube/youtube.py", line 181
    async def qq_download(bot, ev):
IndentationError: unexpected unindent

**Comment by dfmjndm** [comment]
[2022-05-09 00:12:47,903 nonebot] ERROR: Failed to import and load "hoshino.modules.youtube.youtube", error: unexpected unindent (youtube.py, line 181)
[2022-05-09 00:12:47,904 nonebot] ERROR: unexpected unindent (youtube.py, line 181)
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/nonebot/plugin.py", line 419, in _load_plugin
    module = importlib.import_module(module_path)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/hobot/hoshino/modules/youtube/youtube.py", line 181
    async def qq_download(bot, ev):
IndentationError: unexpected unindent
/usr/local/lib/python3.9/site-packages/nonebot/message.py:58: UserWarning: defining message_preprocessor outside a plugin is deprecated and will not be supported in the future
  warnings.warn('defining message_preprocessor outside a plugin is deprecated '

**Comment by haha114514** [comment]
已修改

**Comment by dfmjndm** [comment]
网页下载选项这个114514要改吗

**Comment by dfmjndm** [comment]
推特-网页下载显示：
[2022-07-16 13:09:34,014 下载youtube视频] ERROR: <class 'NameError'> occured when web_download handling message 2024137233.
[2022-07-16 13:09:34,014 下载youtube视频] ERROR: name 'spend_gold' is not defined
Traceback (most recent call last):
  File "/hobot/hoshino/msghandler.py", line 28, in handle_message
    await service_func.func(bot, event)
  File "/hobot/hoshino/modules/youtube_dl_hoshino/youtube.py", line 154, in web_download
    await spend_gold(bot, ev)
NameError: name 'spend_gold' is not defined

**Comment by haha114514** [comment]
请删掉这个spend_gold(bot, ev)，这个是我自己写的积分系统，忘记删掉了
